// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY ?? "";

// Configure Supabase to work around browser storage restrictions
const supabaseOptions = {
  auth: {
    // Disable automatic token refresh to avoid storage issues
    autoRefreshToken: false,
    // Use memory storage instead of localStorage/sessionStorage
    storage: {
      getItem: (key: string) => {
        // Use in-memory storage fallback
        if (typeof window !== 'undefined' && window.sessionStorage) {
          try {
            return window.sessionStorage.getItem(key);
          } catch {
            return null;
          }
        }
        return null;
      },
      setItem: (key: string, value: string) => {
        if (typeof window !== 'undefined' && window.sessionStorage) {
          try {
            window.sessionStorage.setItem(key, value);
          } catch {
            // Silently fail if storage is not available
          }
        }
      },
      removeItem: (key: string) => {
        if (typeof window !== 'undefined' && window.sessionStorage) {
          try {
            window.sessionStorage.removeItem(key);
          } catch {
            // Silently fail if storage is not available
          }
        }
      }
    },
    // Disable persistence to avoid storage issues
    persistSession: false,
    // Detect session from URL only
    detectSessionInUrl: false
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);